const changelog = [
  {
    version: 'Alpha 1.11.0',
    points: [
      'Wood is replaced with Gold, it works the same way.',
      'Surrender button (when playing 1 vs 2).',
      'UI improvements.',
      'Bug fixes.',
    ],
    day: null,
    month: null,
  },
  {
    version: 'Alpha 1.10.0',
    points: ['UI improvements.', 'Bug fixes.'],
    day: null,
    month: null,
  },
  {
    version: 'Alpha 1.9.0',
    points: ['UI improvements.', 'More colors.', 'Bug fixes.'],
    day: null,
    month: null,
  },
  {
    version: 'Alpha 1.8.0',
    points: ['Alliance request notifications.', 'Bug fixes.'],
    day: null,
    month: null,
  },
  {
    version: 'Alpha 1.7.0',
    points: ['Shared vision in an alliance.', 'Several bugs were fixed.'],
    day: 14,
    month: 4,
  },
  {
    version: 'Alpha 1.6.0',
    points: [
      'Redesigned edge of the map.',
      'Cutting trees takes longer, but you get 2 wood instead of 1.',
      'Added spectators mode (on defeat).',
      'Alliances are visible in the leaderboard.',
      'Redesigned "Game over" screen.',
    ],
    day: 12,
    month: 4,
  },
  {
    version: 'Alpha 1.5.1',
    points: [
      'Alliance request timeout set to 20 seconds.',
      'Dead players stay in the leaderboard.',
      'Small bug fixes.',
    ],
    day: 5,
    month: 4,
  },
  {
    version: 'Alpha 1.5.0',
    points: [
      'Added Alliances. If your ally wins, you win too.',
      'Villages are no longer spawning in range of enemy Castles.',
      'Added neutral Villages and Camps.',
    ],
    day: 31,
    month: 3,
  },
  {
    version: 'Alpha 1.4.1',
    points: [
      'Camps are spawning less frequently.',
      'The game automatically finishes after 10 minutes. The player with most tiles wins.',
    ],
    day: 17,
    month: 3,
  },
  {
    version: 'Alpha 1.4.0',
    points: [
      'More responsive armies.',
      'The color selector was moved to waiting screen.',
      'Villages can spawn 2 forests and 2 camps.',
      'Added WASD camera movement.',
      'Improved hover descriptions, it now shows wood costs.',
      'Small graphics improvements & bug fixes.',
    ],
    day: 15,
    month: 3,
  },
  {
    version: 'Alpha 1.3.2',
    points: [
      'The leaderboard is now sorted correctly.',
      'Fixed some small bugs and glitches.',
    ],
    day: 10,
    month: 3,
  },
  {
    version: 'Alpha 1.3.1',
    points: [
      'Faster manual attacks.',
      'Added capture previews.',
      'Fixed many small bugs and glitches.',
    ],
    day: 9,
    month: 3,
  },
  {
    version: 'Alpha 1.3.0',
    points: [
      'Added action queue.',
      'Slower game tempo.',
      'Auto-capture of neutral tiles with >= 5 neighbors.',
      'Smaller world size.',
      'In-game action icons.',
      "Window resize doesn't break the game.",
    ],
    day: 7,
    month: 3,
  },
  {
    version: 'Alpha 1.2.1',
    points: ['Added waiting screen chat.', 'Game is more stable.'],
    day: 3,
    month: 3,
  },
  {
    version: 'Alpha 1.2.0',
    points: [
      'Wood capacity is now 6 instead of 4.',
      'Castle costs 2 wood instead of 1.',
      'Castle starts with a free army.',
      'Game is split into multiple arena instances with 3 - 6 players. Last alive wins.',
      'Capturing a mountain is as fast as any other tile.',
      'Selectable pattern colors.',
      'Manual attacks are a little bit slower.',
      'Several army bugs are fixed.',
    ],
    day: 2,
    month: 3,
  },
  {
    version: 'Alpha 1.1.0',
    points: [
      'Improved Mountain generator.',
      'Escape now cancels Action instead of quitting the game.',
      'Player names are visible on hover.',
      'Added contested tiles icons.',
      'Improved Village spawning algorithm, they never spawn on empire border.',
    ],
    day: 24,
    month: 2,
  },
  {
    version: 'Alpha 1.0.0',
    points: [
      'Every Player starts with 7 tiles, with Capital at center.',
      'Added Hit Points System. Capitals have 2 hit points.',
      'Removed Camps (replaced with Villages and Mountains).',
      'Removed cooldown on Army recruitment.',
      'Removed Action countering system.',
      'Removed Water.',
      'Gold system is replaced with Wood system, with 1 Wood for cutting each Forest tile. Wood is used for building Castles and recruiting armies.',
      'Armies can be used to destroy Castles.',
      'Added Camps with Armies. Randomly spawned by Villages.',
      'Added Villages. Villages spawn on your territory as it grows. Capturing a Village also captures neighboring tiles. Villages randomly spawn Forests and Camps.',
      'Capturing a Mountain also captures neighboring tiles.',
      'Non-neutral Mountains cannot be captured.',
      'Disabled manual attacks on non-neutral tiles.',
      'Disabled manual attacks on neutral tiles with 2 or more neighboring players.',
      'Improved graphics & animations.',
      'Lots of other various changes.',
    ],
    day: 22,
    month: 2,
    editedBy: 'Joeyjojo',
  },
]

export default changelog
