export default [
  ['1', 'capture'],
  ['2', 'unit'],
  ['3', 'lose_tile'],
  ['4', 'forest'],
  ['5', 'building'],
  ['7', 'send_army'],
  ['8', 'gold'],
  ['C', 'clear'],
  ['E', 'castle'],
  ['T', 'village'],
  ['V', 'camp'],
  ['N', 'hp_remove'],
  ['M', 'hp_add'],
  ['6', 'dummy'],
  ['R', 'dummy_capture'],
  ['F', 'dummy_send_army'],
]
